version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cqufsmqj1k6c73dvq8qg-a:5432/postgresql_db_hbuf
      SPRING_DATASOURCE_USERNAME: postgresql_db_hbuf_user
      SPRING_DATASOURCE_PASSWORD: Bp23vdeL7toiqUn1F2URhpU0ukqajMou
    ports:
      - "8081:8081"
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge
